export const LIST_SEARCH_PARAM_KEY = 'keyword'
export const USERNAME_KEY = 'username'
export const PASSWORD_KEY = 'password'
export const List_SEARCH_PARAM_CURRENT = 'current'
export const List_SEARCH_PARAM_PAGE_SIZE = 'pageSize'
